### PR TITLE
Added store method for shortcut two methods (create & update).

### PR DESCRIPTION
**Pull request by maherelgamil**

### CODE REVIEW

**Comment by Omranic** [comment]
Could you please:

1. Move this `store` method to the more appropriate place inside `BaseRepository` under `update` method, and remove it from the `EloquentRepository` class.
2. Add same method to the `Rinvex\Repository\Contracts\RepositoryContract` interface.

Thanks @maherelgamil in advance 😃

**Comment by maherelgamil** [comment]
OK @omranic,  but it's now in Base repository,  I will add it in the RepositoryContract

**Comment by Omranic** [comment]
Thanks @maherelgamil for the PR update, it seems there's a conflict with another recently merged PR, so could you please update your repo, fix the conflict and commit, so we can merge this soon 😄 Thanks again for your appreciated contribution

**Comment by Omranic** [comment]
Needed, so implemented. Thanks anyway @maherelgamil 😄

**Pull request closed without merging**
