### PR TITLE
Get ready for laravel 5.3

### PR DESCRIPTION
**Pull request by rsdev000**
Laravel 5.3 will be out in a month.

### CODE REVIEW

**Comment by Omranic** [comment]
Cool, thanks @rsdev000 
Could you please re-submit the PR to the `develop` branch as we're following `git-flow` 😉 Waiting your update to merge 👍

**Comment by rsdev000** [comment]
Sure. Give me a few minutes. As I said before I have a project that's not "officially" in development but will be in 2 weeks or less and it'll developed on laravel 5.3.
I have good news, not so good news and bad news.

The good news is that your package will be used to manage repositories. It was the first package that me and other colleague found that meet the app requirements. Easy and simple. Other similar packages and an old custom package could be used instead but they don't fit the requirements. I'll suggest more features, bugs, etc but it's what we need and what we want.

The not so good news it's not related with your package. Due to Eloquent limitations - lack of support to composite primary keys - the current database schema demands that we use Doctrine and a package named laravel-doctrine to manage repositories in a specific section of the app.
The database is used by a desktop app and we cannot change that. I also like to have a clean database design and I don't like to add surrogate primary keys (autoincrement ids) when there's an attribute or a set of attributes that uniquely identify a record.

Unfortunately you will not be able to see your work because it's an intranet app and it's not accessible from outside the client company. Only for some people through vpn access. :)

Cheers

**Comment by rsdev000** [comment]
I'm not a pro git user so what´s the best way to re-submit this PR to develop?

**Comment by Omranic** [comment]
Well, I hope you get Eloquent to work for you as it's awesome and save alot of hard work.
I'm glad you find this package useful, just spread the word & feel free to join us at the slack channel: http://chat.rinvex.com

For the PR, I think we can close this one, and you send a new PR to the `develop` branch directly, of course you've to commit on your forked `develop` branch first.

**Comment by rsdev000** [comment]
Let's close this one. I was trying to fork the develop branch but hit on a 403 error
$ git pull upstream develop && git push origin develop
From https://github.com/rinvex/repository
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
remote: Permission to rinvex/repository.git denied to rsdev000.
fatal: unable to access 'https://github.com/rinvex/repository.git/': The requested URL returned error: 403

**Comment by rsdev000** [comment]
Do not have access to the develop branch.

$ git push origin develop
remote: Permission to rinvex/repository.git denied to rsdev000.
fatal: unable to access 'https://github.com/rinvex/repository.git/': The requested URL returned error: 403

**Comment by Omranic** [comment]
You may be interested in this tutorial as you need to fork, clone your fork, commit to your fork, then send pull request from your fork to the original repo 😉 https://guides.github.com/activities/forking/

**Comment by rsdev000** [comment]
Thanks :) Guess it's ok now. I'm a cli guy but the tutorial is great

**Comment by Omranic** [comment]
Merged! cli is the king, I'm a hybrid cli/gui guy 😄

**Pull request closed without merging**
