### PR TITLE
Added store method to repository

### PR DESCRIPTION
**Pull request by maherelgamil**

### CODE REVIEW

**Comment by Omranic** [comment]
So, what's the benefit of this PR? Is there a use case that makes it beneficial not to use `create`, and `update` methods directly, and instead use `store` method?

**Comment by maherelgamil** [comment]
@Omranic It's only shortcutted for these methods.

**Comment by Omranic** [comment]
Well, I could see some benefit here.
Could you please fix code-style issues, and add same method the `Rinvex\Repository\Contracts\RepositoryContract` interface, so we can merge it.. Thanks @maherelgamil in advance 😃

**Comment by Omranic** [comment]
I guess the `store` method is more appropriate to be placed inside `BaseRepository` not within `EloquentRepository`

**Comment by Omranic** [comment]
Duplicate #75

**Pull request closed without merging**
