### PR TITLE
Cache enhancements

### PR DESCRIPTION
**Pull request by rsdev000**
From Laravel 5.3 onwards, one will be able to cache data in minute fractions. A cache lifetime of 0.5 equals to 30 seconds.
Added a convenience method to skip cache for a specific repository query.

### CODE REVIEW

**Comment by Omranic** [comment]
Hmmmm, isn't that the same functionality here: https://github.com/rinvex/repository#individual-repository-query-cache ?
```php
// Disable cache for this specific repository query
$repository->setCacheLifetime(0);
```

**Comment by rsdev000** [comment]
Yes it is. Just think that's more readable $this->skipCache()->find($id) than $this->setCacheLifetime(0)->find($id)

**Comment by Omranic** [comment]
Hello Dear @rsdev000, First of all thank you for your support. Such support is the core drive for keeping such newly born package under active development 😉 For the PR aforementioned, let's just keep the syntax as it is right now, and check the recent update first. Things has been changed a bit around. 😃 You can test `develop` branch & tell your thoughts. It will be tagged as `v2.0.0` once confirmed as stable.

**Comment by rsdev000** [comment]
Will test :)

**Comment by Omranic** [comment]
Yeah, please.
Pushed all commits & testing locally myself.
Please report any issues you encounter, or enhancement ideas 👍

**Comment by rsdev000** [comment]
Not bug nor issue: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Cache/Repository.php

Lifetime float|int

**Comment by Omranic** [comment]
Thanks, considered 👍

**Comment by rsdev000** [comment]
In my humble opinion, the most important feature is the ability to run and cache complex queries with the query bulder: complex joins, raw sql, etc.
With this in hand all new features are bonuses :)

**Comment by Omranic** [comment]
So, how do you see recent update fitting that goal of running complex queries?
What stands out, and what's missing in your opinion?

**Comment by rsdev000** [comment]
It's much better now with where queries with "boolean" param, whereIn, whereNotIn and it fits most of the average app needs but sometimes is not enough. I have some queries in the desktop app that must be replicated in the web app with 20+ lines: several joins, sub selects, aggregates (sum, avg, max), etc.

I can only achieve the same sql with the query builder. In the worst case scenario, the queries will be hardcoded and executed with the query builder.

Just need a method to get a query builder instance and execute / cache the results:
get qb instance:  $this->model->query()->getQuery();

Laravel docs has several examples: https://laravel.com/docs/5.2/queries

Another change in Laravel 5.3 is that query builder results will be collections and not arrays. Don't know if it will be optional or default.

Cheers

**Comment by Omranic** [comment]
Well, if we can extract something generic I'll be happy to implement; Otherwise you can implement your complex logic in your repository & utilize same level or caching as follows:
```php
public function customQuery($attributes = ['*'])
{
    return $this->executeCallback(get_called_class(), __FUNCTION__, func_get_args(), function () use ($attributes) {
        $builder = $this->createModel()->query();
        // Your custom logic
        return $result;
    });
}
```

**Comment by rsdev000** [comment]
Something generic would be nice but custom queries makes my app happy :)

**Pull request closed without merging**
